###############################################################################
# COPYRIGHT (C) 2010.  ARM.  All Rights Reserved. 
#
# THIS FILE INITIALLY CREATED WITH:  
#     TEMPLATE NAME:  make_file.template 
#     COMMAND NAME:   genmake -comp afl -type exe -out libcds_test 
#
# REPOSITORY INFORMATION: 
#  $Revision$ 
#  $Author$ 
#  $Date$ 
#
# _____________________________________________________________________________
#
#  You should never have to alter this file in any way other than the key-value
#  pairs below.  If you want to  override/add definitions or rules, you need to
#  use an auxiliary Makefile.  The definitions/rules files use the variables in
#  the auxiliary file.  You are free to add new variables to this auxiliary
#  Makefile, but keep in mind that these variables should be stuffed into
#  existing variables so that the templates can incorporate them.  See the
#  documentation for auxiliary makefiles by looking at one of them.
###############################################################################
# These variables are needed by the templates ALWAYS
MAIN_MF      := $(shell getsetup -make)
MAKE_TYPE    := exe
COMP_NAME    := afl
BITS64       := true
OUT_NAME      = libcds3.test
# This is the main makefile template
include $(MAIN_MF)
