#******************************************************************************
#
#  COPYRIGHT (C) 2012 Battelle Memorial Institute.  All Rights Reserved.
#
#******************************************************************************
#
#  Author:
#     name:  Jeff Daily
#     phone: (509) 372-6548
#     email: jeff.daily@pnnl.gov
#
#******************************************************************************
cimport cdsproc3_enums

DSP_RETRIEVER = cdsproc3_enums.DSP_RETRIEVER
DSP_RETRIEVER_REQUIRED = cdsproc3_enums.DSP_RETRIEVER_REQUIRED
DSP_TRANSFORM = cdsproc3_enums.DSP_TRANSFORM
DSP_INGEST = cdsproc3_enums.DSP_INGEST

PM_GENERIC = cdsproc3_enums.PM_GENERIC
PM_RETRIEVER_VAP = cdsproc3_enums.PM_RETRIEVER_VAP
PM_TRANSFORM_VAP = cdsproc3_enums.PM_TRANSFORM_VAP
PM_INGEST = cdsproc3_enums.PM_INGEST

DSR_INPUT = cdsproc3_enums.DSR_INPUT
DSR_OUTPUT = cdsproc3_enums.DSR_OUTPUT

VAR_SKIP_TRANSFORM = cdsproc3_enums.VAR_SKIP_TRANSFORM

SUCCESS = cdsproc3_enums.DSPROC_SUCCESS
ENOMEM = cdsproc3_enums.DSPROC_ENOMEM
ENODATA = cdsproc3_enums.DSPROC_ENODATA
EINITSIGS = cdsproc3_enums.DSPROC_EINITSIGS
ERUNTIME = cdsproc3_enums.DSPROC_ERUNTIME
EDSPATH = cdsproc3_enums.DSPROC_EDSPATH
ELOGSPATH = cdsproc3_enums.DSPROC_ELOGSPATH
ELOGOPEN = cdsproc3_enums.DSPROC_ELOGOPEN
EPROVOPEN = cdsproc3_enums.DSPROC_EPROVOPEN
EMAILINIT = cdsproc3_enums.DSPROC_EMAILINIT
EDBERROR = cdsproc3_enums.DSPROC_EDBERROR
EDBCONNECT = cdsproc3_enums.DSPROC_EDBCONNECT
EDQRDBERROR = cdsproc3_enums.DSPROC_EDQRDBERROR
EDQRDBCONNECT = cdsproc3_enums.DSPROC_EDQRDBCONNECT
EDIRLIST = cdsproc3_enums.DSPROC_EDIRLIST
EBADINDSC = cdsproc3_enums.DSPROC_EBADINDSC
EBADOUTDSC = cdsproc3_enums.DSPROC_EBADOUTDSC
EBADDSID = cdsproc3_enums.DSPROC_EBADDSID
EMINTIME = cdsproc3_enums.DSPROC_EMINTIME
EFUTURETIME = cdsproc3_enums.DSPROC_EFUTURETIME
ETIMEORDER = cdsproc3_enums.DSPROC_ETIMEORDER
ETIMEOVERLAP = cdsproc3_enums.DSPROC_ETIMEOVERLAP
EFILECOPY = cdsproc3_enums.DSPROC_EFILECOPY
EFILEMOVE = cdsproc3_enums.DSPROC_EFILEMOVE
EFILEOPEN = cdsproc3_enums.DSPROC_EFILEOPEN
EFILESTATS = cdsproc3_enums.DSPROC_EFILESTATS
EUNLINK = cdsproc3_enums.DSPROC_EUNLINK
ENOSRCFILE = cdsproc3_enums.DSPROC_ENOSRCFILE
ENOFILETIME = cdsproc3_enums.DSPROC_ENOFILETIME
EDESTDIRMAKE = cdsproc3_enums.DSPROC_EDESTDIRMAKE
ETIMECALC = cdsproc3_enums.DSPROC_ETIMECALC
EFILEMD5 = cdsproc3_enums.DSPROC_EFILEMD5
EMD5CHECK = cdsproc3_enums.DSPROC_EMD5CHECK
ECDSALLOCVAR = cdsproc3_enums.DSPROC_ECDSALLOCVAR
ECDSCOPYVAR = cdsproc3_enums.DSPROC_ECDSCOPYVAR
ECLONEVAR = cdsproc3_enums.DSPROC_ECLONEVAR
ECDSDEFVAR = cdsproc3_enums.DSPROC_ECDSDEFVAR
ECDSDELVAR = cdsproc3_enums.DSPROC_ECDSDELVAR
ECDSCOPY = cdsproc3_enums.DSPROC_ECDSCOPY
ECDSCHANGEATT = cdsproc3_enums.DSPROC_ECDSCHANGEATT
ECDSSETATT = cdsproc3_enums.DSPROC_ECDSSETATT
ECDSSETDIM = cdsproc3_enums.DSPROC_ECDSSETDIM
ECDSSETDATA = cdsproc3_enums.DSPROC_ECDSSETDATA
ECDSSETTIME = cdsproc3_enums.DSPROC_ECDSSETTIME
ECDSGETTIME = cdsproc3_enums.DSPROC_ECDSGETTIME
ENODOD = cdsproc3_enums.DSPROC_ENODOD
ENORETRIEVER = cdsproc3_enums.DSPROC_ENORETRIEVER
EBADRETRIEVER = cdsproc3_enums.DSPROC_EBADRETRIEVER
EREQVAR = cdsproc3_enums.DSPROC_EREQVAR
ERETRIEVER = cdsproc3_enums.DSPROC_ERETRIEVER
ENCOPEN = cdsproc3_enums.DSPROC_ENCOPEN
ENCREAD = cdsproc3_enums.DSPROC_ENCREAD
ENOTRANSFORM = cdsproc3_enums.DSPROC_ENOTRANSFORM
ETRANSFORM = cdsproc3_enums.DSPROC_ETRANSFORM
ETRANSPARAMLOAD = cdsproc3_enums.DSPROC_ETRANSPARAMLOAD
EVARMAP = cdsproc3_enums.DSPROC_EVARMAP

LIB_NAME = cdsproc3_enums.DSPROC_LIB_NAME

DS_STANDARD_QC = cdsproc3_enums.DS_STANDARD_QC
DS_FILTER_NANS = cdsproc3_enums.DS_FILTER_NANS
DS_OVERLAP_CHECK = cdsproc3_enums.DS_OVERLAP_CHECK
DS_PRESERVE_OBS = cdsproc3_enums.DS_PRESERVE_OBS
DS_DISABLE_MERGE = cdsproc3_enums.DS_DISABLE_MERGE
DS_SKIP_TRANSFORM = cdsproc3_enums.DS_SKIP_TRANSFORM

DSF_NETCDF = cdsproc3_enums.DSF_NETCDF
DSF_RAW = cdsproc3_enums.DSF_RAW
DSF_PNG = cdsproc3_enums.DSF_PNG
DSF_JPG = cdsproc3_enums.DSF_JPG
