################################################################################
# RCS INFORMATION:
#   $Author: younkin $
#   $Locker:  $
#   $Revision: 1.11 $
#   $Date: 2008/05/22 18:46:06 $
#   $Name: armcm-swawtdev-2#4-0 $
#   $State: armcm-swawtdev-2.4-0 $
#
# PURPOSE:
#   Define template information for the makefile generator for those who
#   need to use IDL software.
#
# DESCRIPTION:
#   To use IDL software, license information must be used in the Makefile in
#   order to compile IDL files.  That information is stored in this file and
#   must have the name Makedefs.idl.  SWAWT will look for this file and use its
#   contents to build any IDL software.
#
# These are the IDL 6 license data needed (in command line format)
#        IDL> SAVE, /ROUTINES, EMBEDDED=[ $
#                'Battelle Pacific Northwest National Laboratory', $
#                'ARM Data System', $
#                'IDL 6.0', $
#                'W8GFJPF4'], FILE='EMBED.SAV'
#
################################################################################


idl_version := $(shell basename $(IDL_DIR))
IDL_PATH := "+$(IDL_DIR)/lib:$(IDL_PATH)"

ifeq ($(idl_version),idl_6.0)

  IDL_CO  := Battelle Pacific Northwest National Laboratory
  IDL_APP := ARM Data System
  IDL_VER := IDL 6.0
  IDL_LIC := W8GFJPF4
  IDL_KEY := [\'$(IDL_CO)\',\'$(IDL_APP)\',\'$(IDL_VER)\',\'$(IDL_LIC)\']

endif

ifeq ($(idl_version),idl_5.4)

    IDL_CO  := Battelle Pacific Northwest National Laboratory
    IDL_APP := ARM Data Application
    IDL_LIC := 7JKBYZUZ
    IDL_KEY := [\'$(IDL_CO)\', \'$(IDL_APP)\', \'$(IDL_LIC)\']

endif

ifeq ($(idl_version),idl_6.2)
    IDL_CO  := Battelle Pacific Northwest National Laboratory
    IDL_APP := ARM Data System
    IDL_VER := IDL 6.2
    IDL_LIC := W2HGLFFG
    IDL_KEY := [\'$(IDL_CO)\',\'$(IDL_APP)\',\'$(IDL_VER)\',\'$(IDL_LIC)\']

endif


IDL_EMBED  = embedded=$(IDL_KEY)

ifeq ($(idl_version),idl71)
IDL_EMBED = '/embedded'
endif
ifeq ($(idl_version),idl80)
IDL_EMBED = '/embedded'
endif
ifeq ($(idl_version),idl81)
IDL_EMBED = '/embedded'
endif
ifeq ($(idl_version),idl82)
IDL_EMBED = '/embedded'
endif
